FROM mysql:latest
RUN chown -R mysql:root /var/lib/mysql/

ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD

ENV MYSQL_DATABASE=$ems
ENV MYSQL_USER=$root
ENV MYSQL_PASSWORD=$1234
ENV MYSQL_ROOT_PASSWORD=$1234


RUN /bin/bash -c "/usr/bin/mysqld_safe --skip-grant-tables &" && \
  sleep 5 && \
  mysql -u root -e "CREATE DATABASE ems" && \
  mysql -u root ems < /tmp/dump.sql

EXPOSE 3306
